# Generated by Django 3.1.1 on 2020-09-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=255, verbose_name='Lecture Title')),
                ('lecture_slug', models.SlugField(verbose_name='Lecture Slug')),
                ('lecture_description', models.TextField(blank=True, null=True, verbose_name='Lecture Description')),
                ('lecture_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('lecture_video', models.CharField(max_length=150, verbose_name='Video ID')),
                ('lecture_previewable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Is Previewable?')),
                ('lecture_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('lecture_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('seo_lecture_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Lecture Title (60 Characters Long)')),
                ('seo_lecture_keyword', models.TextField(blank=True, null=True, verbose_name='SEO Lecture Keywords, Separated by Comma')),
                ('seo_lecture_description', models.TextField(blank=True, null=True, verbose_name='SEO Lecture Description (160 Characters Long)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
