# Generated by Django 3.1.1 on 2020-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_video',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
    ]
